import type {Trip} from '@/generated/prisma/client';

type TripFormData = Partial<Trip> & {priceFrom?: unknown};
const pretty=(value:unknown)=>JSON.stringify(value??[],null,2);
export function TripAdminForm({trip,action,submitLabel,defaultCurrency='USD'}:{trip?:TripFormData;action:(formData:FormData)=>void|Promise<void>;submitLabel:string;defaultCurrency?:'USD'|'EUR'|'GBP'}){return <form action={action} className="mt-7 grid gap-5 rounded-3xl border bg-white p-5 sm:p-7">
<div className="grid gap-5 sm:grid-cols-2"><Field label="Slug"><input name="slug" defaultValue={trip?.slug??''} required placeholder="orange-bay" className="input"/></Field><Field label="Title"><input name="title" defaultValue={trip?.title??''} required className="input"/></Field></div>
<div className="grid gap-5 sm:grid-cols-3"><Field label="Category"><select name="category" defaultValue={trip?.category??'islands-snorkeling'} required className="input"><option value="culture">Culture & History</option><option value="islands-snorkeling">Islands & Snorkeling</option><option value="diving-sea">Diving & Sea</option><option value="desert-adventure">Desert & Adventure</option><option value="family-city">Family & City</option><option value="private">Private Trips</option></select></Field><Field label="Category label"><input name="categoryLabel" defaultValue={trip?.categoryLabel??'Islands & Snorkeling'} required className="input"/></Field><Field label="Eyebrow"><input name="eyebrow" defaultValue={trip?.eyebrow??''} className="input"/></Field></div>
<Field label="Short description"><textarea name="shortDescription" defaultValue={trip?.shortDescription??''} rows={5} required className="input"/></Field>
<div className="grid gap-5 sm:grid-cols-3"><Field label="Duration"><input name="duration" defaultValue={trip?.duration??''} className="input"/></Field><Field label="Price"><input name="priceFrom" type="number" step="0.01" defaultValue={trip?.priceFrom?String(trip.priceFrom):'0'} className="input"/></Field><Field label="Currency"><select name="currency" defaultValue={trip?.currency??defaultCurrency} className="input"><option value="USD">USD</option><option value="EUR">EUR</option><option value="GBP">GBP</option></select></Field></div>
<div className="grid gap-5 sm:grid-cols-2"><Field label="Status"><select name="status" defaultValue={trip?.status??'draft'} className="input"><option value="published">Published</option><option value="draft">Draft</option><option value="disabled">Disabled</option></select></Field><Field label="Sort order"><input name="sortOrder" type="number" defaultValue={trip?.sortOrder??100} className="input"/></Field></div>
<div className="flex flex-wrap gap-6"><label className="flex items-center gap-2 font-bold"><input name="featured" type="checkbox" defaultChecked={trip?.featured??false}/>Featured</label><label className="flex items-center gap-2 font-bold"><input name="popular" type="checkbox" defaultChecked={trip?.popular??false}/>Popular</label></div>
<Field label="Hero image path"><input name="heroImage" defaultValue={trip?.heroImage??''} placeholder="/images/trips/orange-bay-1.webp" className="input"/></Field>
<div className="grid gap-5 lg:grid-cols-2"><JsonField name="gallery" label="Gallery — JSON array" value={pretty(trip?.gallery)}/><JsonField name="highlights" label="Highlights — JSON array" value={pretty(trip?.highlights)}/><JsonField name="itinerary" label="Itinerary — JSON array" value={pretty(trip?.itinerary)}/><JsonField name="included" label="Included — JSON array" value={pretty(trip?.included)}/><JsonField name="excluded" label="Not included — JSON array" value={pretty(trip?.excluded)}/><JsonField name="whatToBring" label="What to bring — JSON array" value={pretty(trip?.whatToBring)}/></div>
<Field label="WhatsApp message"><textarea name="whatsappMessage" defaultValue={trip?.whatsappMessage??''} rows={3} className="input"/></Field><Field label="SEO title"><input name="seoTitle" defaultValue={trip?.seoTitle??''} className="input"/></Field><Field label="SEO description"><textarea name="seoDescription" defaultValue={trip?.seoDescription??''} rows={3} className="input"/></Field>
<button className="min-h-12 rounded-xl bg-slate-950 px-5 font-black text-white">{submitLabel}</button></form>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-2 text-sm font-bold text-slate-700">{label}{children}</label>}
function JsonField({label,name,value}:{label:string;name:string;value:string}){return <Field label={label}><textarea name={name} defaultValue={value} rows={8} spellCheck={false} className="input font-mono text-xs"/></Field>}
