import {prisma} from '@/lib/database/prisma';
import {createReview, deleteReview, updateReview, updateReviewStatus} from '@/features/admin/actions';

export default async function ReviewsPage() {
  const reviews = await prisma.review.findMany({orderBy: [{sortOrder: 'asc'}, {createdAt: 'desc'}], take: 200});
  return <main className="p-4 sm:p-6 lg:p-8"><div className="mx-auto max-w-6xl">
    <div><h1 className="text-3xl font-black">Reviews</h1><p className="mt-2 text-slate-600">Add only genuine customer reviews. Draft reviews never appear publicly.</p></div>
    <form action={createReview} className="mt-7 grid gap-4 rounded-3xl border bg-white p-5 sm:grid-cols-2 sm:p-7">
      <Field label="Customer name"><input name="name" required className="input"/></Field>
      <Field label="Country"><input name="country" className="input"/></Field>
      <Field label="Rating"><select name="rating" defaultValue="5" className="input">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></Field>
      <Field label="Trip slug — optional"><input name="tripSlug" placeholder="orange-bay" className="input"/></Field>
      <Field label="Title — optional"><input name="title" className="input"/></Field>
      <Field label="Status"><select name="status" defaultValue="draft" className="input"><option value="draft">Draft</option><option value="published">Published</option></select></Field>
      <div className="sm:col-span-2"><Field label="Review text"><textarea name="text" required rows={4} className="input"/></Field></div>
      <Field label="Sort order"><input name="sortOrder" type="number" defaultValue="100" min="0" className="input"/></Field>
      <div className="flex items-end"><button className="min-h-12 rounded-xl bg-slate-950 px-5 text-sm font-black text-white">Add review</button></div>
    </form>
    <div className="mt-7 grid gap-4">{reviews.length===0?<div className="rounded-2xl border border-dashed bg-white p-8 text-center text-slate-500">No reviews added yet.</div>:reviews.map(review=><article key={review.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-black">{review.name} · {review.rating}/5</div><div className="mt-1 text-xs text-slate-400">{review.country||'Country not set'} {review.tripSlug?`· ${review.tripSlug}`:''} · {review.createdAt.toLocaleDateString()}</div></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold uppercase">{review.status}</span></div>{review.title?<h2 className="mt-4 font-black">{review.title}</h2>:null}<p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-700">{review.text}</p><details className="mt-4 rounded-xl border bg-slate-50 p-4"><summary className="cursor-pointer text-sm font-black">Edit review</summary><form action={updateReview.bind(null,review.id)} className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Customer name"><input name="name" defaultValue={review.name} required className="input"/></Field><Field label="Country"><input name="country" defaultValue={review.country||''} className="input"/></Field><Field label="Rating"><select name="rating" defaultValue={String(review.rating)} className="input">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></Field><Field label="Trip slug — optional"><input name="tripSlug" defaultValue={review.tripSlug||''} className="input"/></Field><Field label="Title — optional"><input name="title" defaultValue={review.title||''} className="input"/></Field><Field label="Status"><select name="status" defaultValue={review.status} className="input"><option value="draft">Draft</option><option value="published">Published</option></select></Field><div className="sm:col-span-2"><Field label="Review text"><textarea name="text" defaultValue={review.text} required rows={4} className="input"/></Field></div><Field label="Sort order"><input name="sortOrder" type="number" defaultValue={review.sortOrder} min="0" className="input"/></Field><div className="flex items-end"><button className="min-h-11 rounded-lg bg-slate-950 px-4 text-xs font-black text-white">Save changes</button></div></form></details><div className="mt-4 flex flex-wrap gap-2"><form action={updateReviewStatus.bind(null,review.id,review.status==='published'?'draft':'published')}><button className="rounded-lg border px-3 py-2 text-xs font-bold">{review.status==='published'?'Move to draft':'Publish'}</button></form><form action={deleteReview.bind(null,review.id)}><button className="rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-red-700">Delete</button></form></div></article>)}</div>
  </div></main>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="grid gap-2 text-sm font-bold text-slate-700">{label}{children}</label>}
